services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: order_api_user
      POSTGRES_PASSWORD: order_api_password
      POSTGRES_DB: order_api_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6383:6379'

  localstack:
    image: localstack/localstack:latest
    ports:
      - '4570:4566'
    environment:
      - SERVICES=lambda,apigateway,iam,logs,s3,cloudformation
      - DEBUG=1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  pgdata:
