service: inventory-api

frameworkVersion: '3'

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost:4566
    edgePort: 4566

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'local'}
  memorySize: 512
  timeout: 30
  apiGateway:
    restApiId: nex-gw
    restApiRootResourceId: ${env:API_GW_ROOT_RESOURCE_ID}
  environment:
    NODE_ENV: production
    DATABASE_URL: ${env:DATABASE_URL, 'postgresql://inventory_api_user:inventory_api_password@postgres:5432/inventory_api_db'}
    REDIS_HOST: ${env:REDIS_HOST, 'redis'}
    REDIS_PORT: ${env:REDIS_PORT, '6379'}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD, ''}
    CACHE_TTL: ${env:CACHE_TTL, '300'}
    AWS_ENDPOINT: ${env:AWS_ENDPOINT, 'http://localstack:4566'}
    INVENTORY_ORDER_EVENTS_QUEUE_URL: ${env:INVENTORY_ORDER_EVENTS_QUEUE_URL, 'http://localstack:4566/000000000000/inventory-order-events-queue'}

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: api/inventory
      - http:
          method: ANY
          path: api/inventory/{proxy+}

package:
  individually: true
  patterns:
    - '!**'
    - 'dist/**'
    - 'dist/node_modules/**'
